dist: trusty
language: python
addons:
  chrome: stable
before_script: 
 - wget -N https://chromedriver.storage.googleapis.com/86.0.4240.183/chromedriver_linux64.zip -P ~/
 - unzip ~/chromedriver_linux64.zip -d ~/
 - rm ~/chromedriver_linux64.zip
 - sudo mv -f ~/chromedriver /usr/local/share/
 - sudo chmod +x /usr/local/share/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
 - sudo apt-get install google-chrome-stable
script: python main.py
